[package]
name = "c-layout-impl"
version = "0.1.0"
authors = ["Julian Orth <ju.orth@gmail.com>"]
edition = "2018"

[dependencies]
repr-c-impl = { path = "../../repr-c/impl", version = "0.1.0" }
anyhow = "1.0.38"
