[package]
name = "repr-c-tests"
version = "0.1.0"
authors = ["Julian Orth <ju.orth@gmail.com>"]
edition = "2018"

[dependencies]
repr-c = { path = "../repr-c" }
c-layout-priv = { path = "../c-layout-priv" }
anyhow = "1.0.38"
rayon = "1.5.0"
